export const TotalLanguageList = [
	{ code: 'en', name: 'English (US)' },
	{ code: 'en-GB', name: 'English (UK)' },
	// { code: 'fi', name: 'Suomi - Finnish' },
	// { code: 'da', name: 'Dansk - Danish' },
	// { code: 'fr', name: 'Français - French' },
	// { code: 'cy', name: 'Cymraeg - Welsh' },
	// { code: 'de', name: 'Deutsch - German' },
	// { code: 'it', name: 'Italiano - Italian' },
	{ code: 'es', name: 'Español - Spanish' },
	// { code: 'pt-PT', name: 'Português - Portuguese' },
	// { code: 'pt-BR', name: 'Português - Portuguese (Brazil)' },
	// { code: 'ja', name: '日本語 - Japanese' },
	// { code: 'my', name: 'ဗမာ - Burmese' },
];
